# Generated by Django 4.1.1 on 2022-11-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_messages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='image',
        ),
        migrations.AddField(
            model_name='messages',
            name='type',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
